trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      docker-compose build
    displayName: 'Build Docker Images'

  - script: |
      docker-compose up -d
    displayName: 'Run Docker Containers'
